# Created by Makrand
version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev

    ports:
      - "9010:3000"

    volumes:
      - .:/app
  test:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app


